apiVersion: v1
kind: Service
metadata:
  name: cloud-wallet-service
  namespace: cloud-wallet

spec:
  selector:
    app: cloud-wallet

  type: NodePort

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080